name: CI tooling
on: pull_request

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        ruby: ["2.6", "3.2"]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
      - run: bundle install && ruby app.test.rb
